import type { Book } from "./types";

export const BOOKS: Book[] = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    coverImage: "./src/asset/img2.jpg",
    status: "unread",
    pages: 320,
    genre: "Self-help",
    addedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Deep Work",
    author: "Cal Newport",
    coverImage: "./src/asset/img1.jpg",
    status: "unread",
    pages: 280,
    genre: "Productivity",
    addedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "no one",
    author: "three-thing",
    coverImage: "./src/asset/img3.webp",
    status: "unread",
    pages: 240,
    genre: "self-help",
    addedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    coverImage: "./src/asset/img1.jpg",
    status: "unread",
    pages: 280,
    genre: "Personal Finance",
    addedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "one thing",
    author: "Gary Keller",
    coverImage: "./src/asset/img1.jpg",
    status: "unread",
    pages: 280,
    genre: "Productivity",
    addedAt: new Date().toISOString(),
  },
];